# Generated by Django 5.0.6 on 2024-09-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': True, 'verbose_name': 'المواد', 'verbose_name_plural': 'المواد'},
        ),
        migrations.AlterModelTable(
            name='subject',
            table='',
        ),
    ]
