# Generated by Django 5.0.6 on 2024-09-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0005_remove_user_package_remove_user_subjects_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceInfo',
        ),
    ]
