# Generated by Django 5.0.6 on 2024-09-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0006_delete_deviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(default='رابط .. ', max_length=200, verbose_name='رابط المحاضرة الخاصة')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'المواد',
                'verbose_name_plural': 'المواد',
            },
        ),
    ]
