# Generated by Django 5.0.6 on 2024-09-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0007_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
